### ISSUE TITLE
Issue 1

### ISSUE THREAD

**Issue by MinhPT-99** [morted/morted.github.io#1]
Bài làm tốt, chuẩn form. Tuy nhiên có một lỗi nho nhỏ. E tạo quá nhiều thẻ p, thay vào đó e hãy dùng thẻ br để xuống dòng nhé. A muốn hỏi 1 câu như sau: E có thấy những thuộc tính như width, height hay text-align phải viết đi viết lại giống nhau và rất nhiều lần không? Giải quyết như thế nào được nhỉ? :C giúp a nhé

**Comment by morted** [comment]
e sửa xong rồi. anh check lại giúp e ak

**Comment by minhpt99** [comment]
ok
